### ISSUE TITLE
Add rgb matrix for the scylla

### ISSUE THREAD

**Issue by bstiq** [Bastardkb/vial-firmware#1]
We'd like to add rgb matrix to the scylla in vial.

@steven-y-e already implemented it, do you mind if we reuse it?

**Comment by steven-y-e** [comment]
Uhh, i don’t recall doing anything like that? Did you mean to tag someone else?

**Comment by bstiq** [comment]
@steven-y-e here? https://irie.clinic.homo.casa/steven-y-e/qmk/src/commit/b29179de1afc1daaeacfc8685a1d69be13dc5d0e/keyboards/bastardkb/scylla/scylla.c

**Comment by steven-y-e** [comment]
that’s just a copy of qmk that i threw up onto a personal git server

https://github.com/qmk/qmk_firmware/tree/master/keyboards/bastardkb/scylla

i believe @filterpaper is the contributor who wrote the rgb matrix support for scylla

**Comment by bstiq** [comment]
Allright, thanks !
